# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               Level Drain
tagline:             'You're here forever'
description:         'An OSR trove od bad ideas'
url:                 https://thevinter.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nik Vinter
  url:               github.com/thevinter
  email:             nikita.brancatisano@gmail.com

# Custom vars
version:             1.3.0

analytics:
  provider: "google-universal"
  google:
  tracking_id: "G-QSHJ72JD2X"

